version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASS}
      PGDATA: ${PGDATA}
    volumes:
      - ${VOLUME_ENTRY}
      - ${VOLUME_DATA}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080