version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "weatherDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123321"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/entry:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
